# Generated by Django 4.2.7 on 2025-10-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_make_nickname_required'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
