# Generated by Django 4.2.7 on 2025-10-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_moderation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
